<a href="https://colab.research.google.com/github/mirrorball108/EEG-analysis-of-Autism-patients/blob/main/autism_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_pre=pd.read_csv('/content/pre_treatement_combined.csv')


In [ ]:
df_pre.head()

FP2-F4  F4 -C4  C4 -P4  P4 -O2  FP1-F3  F3 -C3  C3 -P3  P3 -O1  FP2-F8  \
0     -65       3     -16      20       5      -4     -65      84      26   
1    -108      41     -17      16     -28     183     -85      79      22   
2    -177     102     -20      12     -84     481    -113      69      16   
3    -270     177     -23       6    -157     849    -145      55       2   
4    -383     260     -26      -1    -242    1250    -178      37     -21   

   F8 -T4  T4 -T6  T6 -O2  FP1-F7  F7 -T3  T3 -T5  T5 -O1  
0     -71      -7      -8      76     -40     -44      28  
1     -86       5     -10     201     -12     -42       2  
2    -111      25     -14     402      30     -41     -38  
3    -144      51     -19     647      81     -40     -87  
4    -184      80     -26     911     137     -42    -140

In [ ]:
df_post=pd.read_csv('/content/post_treatment_combined.csv')
df_post.head()


FP2-F4  F4 -C4  C4 -P4  P4 -O2  FP1-F3  F3 -C3  C3 -P3  P3 -O1  FP2-F8  \
0     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1   -74.0     7.0   -15.0   -69.0    19.0   -23.0   -23.0   -36.0   -21.0   
2   -74.0     4.0   -16.0   -53.0     1.0   -15.0   -22.0   -32.0   -24.0   
3   -92.0     0.0   -14.0   -31.0   -28.0    -5.0   -20.0   -26.0   -47.0   
4  -126.0    -3.0   -12.0   -12.0   -61.0     5.0   -17.0   -21.0   -89.0   

   F8 -T4  T4 -T6  T6 -O2  FP1-F7  F7 -T3  T3 -T5  T5 -O1  
0     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
1   -46.0   -54.0   -30.0     4.0   -41.0     5.0   -30.0  
2   -47.0   -56.0   -13.0    -8.0   -43.0     7.0   -24.0  
3   -42.0   -57.0     9.0   -28.0   -46.0    12.0   -17.0  
4   -32.0   -57.0    24.0   -52.0   -48.0    18.0   -12.0

In [ ]:
df_post=df_post.drop([0,1])

In [ ]:
df_post.head()

FP2-F4  F4 -C4  C4 -P4  P4 -O2  FP1-F3  F3 -C3  C3 -P3  P3 -O1  FP2-F8  \
2   -74.0     4.0   -16.0   -53.0     1.0   -15.0   -22.0   -32.0   -24.0   
3   -92.0     0.0   -14.0   -31.0   -28.0    -5.0   -20.0   -26.0   -47.0   
4  -126.0    -3.0   -12.0   -12.0   -61.0     5.0   -17.0   -21.0   -89.0   
5  -163.0    -5.0   -10.0    -5.0   -85.0    10.0   -13.0   -18.0  -136.0   
6  -188.0    -6.0    -9.0    -8.0   -91.0    10.0   -10.0   -18.0  -171.0   

   F8 -T4  T4 -T6  T6 -O2  FP1-F7  F7 -T3  T3 -T5  T5 -O1  
2   -47.0   -56.0   -13.0    -8.0   -43.0     7.0   -24.0  
3   -42.0   -57.0     9.0   -28.0   -46.0    12.0   -17.0  
4   -32.0   -57.0    24.0   -52.0   -48.0    18.0   -12.0  
5   -19.0   -55.0    28.0   -72.0   -47.0    22.0    -9.0  
6    -8.0   -53.0    20.0   -82.0   -45.0    23.0    -7.0

In [ ]:
df_pre.size

122880

In [ ]:
df_pre.shape

(7680, 16)

In [ ]:
df_post.shape

(7679, 16)

In [ ]:
#creating labels
pre=[1]*7680
post=[0]*7679

print(pre[0:5])
print(post[0:5])

labels=pre+post
print(len(labels))
type(labels)

[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]
15359


list

In [ ]:
df = pd.concat([df_pre, df_post], ignore_index=True)

In [ ]:
df.shape

(15359, 16)

In [ ]:
#check empty values
df.isna().any(axis=1).sum()

np.int64(0)

In [ ]:
#feature scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df_scaled = sc.fit_transform(df)

In [ ]:
#compute covariance matrix
cov_matrix=np.cov(df_scaled.T)
cov_matrix

array([[ 1.00006511,  0.19151301,  0.15364184, -0.00985169,  0.76930561,
         0.1608413 ,  0.14275534,  0.06185519,  0.89310973, -0.05110664,
         0.07475542, -0.12109013,  0.70185005,  0.0179659 ,  0.14552052,
        -0.1201929 ],
       [ 0.19151301,  1.00006511,  0.09038823,  0.1997115 , -0.04186753,
         0.47563617,  0.22668683, -0.31391413,  0.43129055, -0.0165197 ,
         0.14106893,  0.45299441,  0.18807211, -0.03371733, -0.03835612,
         0.07126813],
       [ 0.15364184,  0.09038823,  1.00006511,  0.10004465,  0.1718963 ,
         0.02297465,  0.39451999,  0.18316125,  0.22390449,  0.12501759,
         0.43879813,  0.06839829,  0.21916639,  0.08488362, -0.04168409,
         0.18633922],
       [-0.00985169,  0.1997115 ,  0.10004465,  1.00006511, -0.02931075,
         0.20699286,  0.24745491,  0.07332381,  0.06864842,  0.21079726,
         0.12418061,  0.64744807,  0.12853505, -0.09322249,  0.26595201,
        -0.01125318],
       [ 0.76930561, -0.04186753,  0

In [ ]:
#calculate eigen values and eigen vectors
eigen_values,eigen_vectors=np.linalg.eigh(cov_matrix)

In [ ]:
#PCA

from sklearn.decomposition import PCA
pca=PCA(n_components=5)
train_pca=pca.fit_transform(df_scaled)

In [ ]:
#explain variance ratio

pca.explained_variance_ratio_

array([0.23494592, 0.14888988, 0.12538381, 0.10213939, 0.0845847 ])

In [ ]:
pca_df=pd.DataFrame(data=train_pca,columns=['PC1','PC2','PC3','PC4','PC5'])
pca_df.head()

PC1       PC2       PC3       PC4       PC5
0 -0.117572 -0.739789 -0.558825 -0.710430  1.016014
1  0.518156 -0.279092 -1.051223 -1.278945  2.264711
2  1.527306  0.513293 -1.813488 -2.205270  4.207197
3  2.716833  1.526794 -2.717455 -3.366145  6.595840
4  3.930231  2.666595 -3.673966 -4.702385  9.210068

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(pca_df, labels, test_size=0.3, random_state=42)

# Create and train the SVM model
model = SVC(kernel='linear')
model.fit(X_train, y_train)


SVC(kernel='linear')

In [ ]:
# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy Score: {accuracy}")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy Score: 0.5197482638888888
[[1110 1195]
 [1018 1285]]
              precision    recall  f1-score   support

           0       0.52      0.48      0.50      2305
           1       0.52      0.56      0.54      2303

    accuracy                           0.52      4608
   macro avg       0.52      0.52      0.52      4608
weighted avg       0.52      0.52      0.52      4608



In [ ]:


# Split the dataset into training and testing sets
X_train2, X_test2, y_train2, y_test2 = train_test_split(df_scaled, labels, test_size=0.3, random_state=42)

# Create and train the SVM model
model2 = SVC(kernel='linear')
model2.fit(X_train2, y_train2)


SVC(kernel='linear')

In [ ]:
# Make predictions
y_pred2 = model2.predict(X_test2)

# Evaluate the model
accuracy2 = accuracy_score(y_test2, y_pred2)
print(f"Accuracy Score: {accuracy2}")
print(confusion_matrix(y_test2, y_pred2))
print(classification_report(y_test2, y_pred2))

Accuracy Score: 0.578125
[[1116 1189]
 [ 755 1548]]
              precision    recall  f1-score   support

           0       0.60      0.48      0.53      2305
           1       0.57      0.67      0.61      2303

    accuracy                           0.58      4608
   macro avg       0.58      0.58      0.57      4608
weighted avg       0.58      0.58      0.57      4608



In [ ]:
#using random forest with PCA
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
accuracy_rf= accuracy_score(y_test, y_pred_rf)
print(f"Accuracy Score: {accuracy_rf}")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Accuracy Score: 0.8756510416666666
[[1996  309]
 [ 264 2039]]
              precision    recall  f1-score   support

           0       0.88      0.87      0.87      2305
           1       0.87      0.89      0.88      2303

    accuracy                           0.88      4608
   macro avg       0.88      0.88      0.88      4608
weighted avg       0.88      0.88      0.88      4608



In [ ]:
#using random forest without PCA
rf2 = RandomForestClassifier(n_estimators=100, random_state=42)
rf2.fit(X_train2, y_train2)
y_pred_rf2 = rf2.predict(X_test2)
accuracy_rf2= accuracy_score(y_test2, y_pred_rf2)
print(f"Accuracy Score: {accuracy_rf2}")
print(confusion_matrix(y_test2, y_pred_rf2))
print(classification_report(y_test2, y_pred_rf2))

Accuracy Score: 0.9837239583333334
[[2251   54]
 [  21 2282]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      2305
           1       0.98      0.99      0.98      2303

    accuracy                           0.98      4608
   macro avg       0.98      0.98      0.98      4608
weighted avg       0.98      0.98      0.98      4608



In [ ]:
!pip install tensorflow


In [ ]:
#		C4 -P4	P4 -O2			C3 -P3	P3 -O1	FP2-F8		T6 -O2	FP1-F7		T5 -O1

In [ ]:
df_acc_leads=df.drop(columns=['C4 -P4','P4 -O2','C3 -P3','P3 -O1','FP2-F8','T6 -O2','FP1-F7','T5 -O1'])

In [ ]:
#feature scaling
sc2 = StandardScaler()
df_leads_scaled = sc2.fit_transform(df_acc_leads)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
x_train4,x_test4,y_train4,y_test4=train_test_split(df_leads_scaled,labels,test_size=0.2,random_state=42)

In [ ]:
#using random forest
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
rf4 = RandomForestClassifier(n_estimators=100, random_state=42)
rf4.fit(x_train4, y_train4)
y_pred_rf4 = rf4.predict(x_test4)
accuracy_rf4= accuracy_score(y_test4, y_pred_rf4)
print(f"Accuracy Score: {accuracy_rf4}")
print(confusion_matrix(y_test4, y_pred_rf4))
print(classification_report(y_test4, y_pred_rf4))

Accuracy Score: 0.9612630208333334
[[1478   72]
 [  47 1475]]
              precision    recall  f1-score   support

           0       0.97      0.95      0.96      1550
           1       0.95      0.97      0.96      1522

    accuracy                           0.96      3072
   macro avg       0.96      0.96      0.96      3072
weighted avg       0.96      0.96      0.96      3072



In [ ]:
!pip install ydata-profiling


  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.1/400.1 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 19.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.8/687.8 kB 29.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 3.2 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=10815a6b5494acc5305a846c69ae5005df168c6be2dd9d7d480f7fd9d832fb91
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin


In [ ]:
from ydata_profiling import ProfileReport
import seaborn as sns

profile = ProfileReport(df, title="Autism Dataset EDA", explorative=True)
profile.to_file("autism_eda.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|██████████| 16/16 [00:00<00:00, 67.85it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
import webbrowser
webbrowser.open('autism_eda.html')


False